spring:
  application:
    name: turnstile
  profiles:
    active: prod
rate-limiter:
  bucket:
    key: ratelimit
    capacity: 5
    refill-token-amount: 1
    refill-interval-seconds: 60

---
server:
  port: 8080

spring:
  config:
    activate:
      on-profile: prod
  data:
    redis:
      host: redis
      port: 6379

---
server:
  port: 8090

spring:
  config:
    activate:
      on-profile: dev
  data:
    redis:
      host: localhost
      port: 6379